(define in (call-with-input-file "./input.txt" read))
(define names (map name in))
(define (child? child tower) (memq (name child) (children tower)))
(define (children tower) (cddr tower))
(define (weight tower) (cadr tower))
(define (name tower) (car tower))
(define (find-root towers roots)
  (if (null? towers)
      (car roots)
      (find-root (cdr towers) (remove (lambda (r) (child? r (car towers)))
				      roots))))

